### PR TITLE
Remove @electron/remote dependency

### PR DESCRIPTION
**Pull request by TimoshN**
+ remove @electron/remote
+ use ipcRenderer.invoke to open dialog
+ get userData path via ipcRenderer.sendSync on start

### CODE REVIEW

**Comment by Stanzilla** [comment]
Oh nice, what's the motivation behind it apart from removing the dependency? I might still need it in the v5 branch but not sure.

**Comment by TimoshN** [comment]
Mostly because of this https://www.electronjs.org/docs/latest/breaking-changes#deprecated-remote-module

**Comment by Stanzilla** [comment]
But that was a while back and we already moved from to @electron/remote?

**Comment by TimoshN** [comment]
`Warning! This module has many subtle pitfalls. There is almost always a better way to accomplish your task than using this module. For example, ipcRenderer.invoke can serve many common use cases.` 

Warning message from @electron/remote repo

**Comment by Stanzilla** [comment]
Oh okay!

**Pull request merged**
