### PR TITLE
Turkish Language Support and Editable "Get yours" String

### PR DESCRIPTION
**Pull request by kendinikertenkelebek**
This PR contains Turkish language support and untranslatable "Get yours" string moved to language files.

### CODE REVIEW

**Comment by kendinikertenkelebek** [comment]
very interesting unsuccessful checks.

**Comment by Stanzilla** [comment]
Oh good find, I need to fix GitHub actions for pull requests

**Comment by Stanzilla** [comment]
Thank you!

**Comment by kendinikertenkelebek** [comment]
your welcome! but all 28th lines in translation files must be re-write (excluding Turkish and English of course). I don't know other languages sorry about that.

**Pull request merged**
