### PR TITLE
Move to Vite

### PR DESCRIPTION
**Pull request by Stanzilla**
This moves our codebase from using vue-cli to its successor, vite.

### CODE REVIEW

**Comment by Stanzilla** [comment]
@caoxiemeihao Hey there, I saw your vite electron plugins changed a lot, what would be the new suggested / best way to load our external libraries like `sharp` etc now?

**Comment by caoxiemeihao** [comment]
> @caoxiemeihao Hey there, I saw your vite electron plugins changed a lot, what would be the new suggested / best way to load our external libraries like `sharp` etc now?

Yep! Starting from `vite-plugin-electron-renderer@0.10.2` again, external libraries are built-in support.
👉 [example](https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.10.3/examples/quick-start/vite.config.ts#L14-L23)

```js
{
  plugins: [
    renderer({
      // Enables use of Node.js API in the Renderer-process
      nodeIntegration: true,
      // Like Vite's pre bundling
      optimizeDeps: {
        include: [
          'sharp', // Here
        ],
      },
    }),
  ],
}
```

> Also do we really have to load these dependencies and if so, why? I never quite understood that. [f70971d](https://github.com/WeakAuras/WeakAuras-Companion/commit/f70971d273f8c731ad42d05b03c76edf66707079)

This is not required, it optimizes the size of the APP package after the build.

**Comment by Stanzilla** [comment]
> > @caoxiemeihao Hey there, I saw your vite electron plugins changed a lot, what would be the new suggested / best way to load our external libraries like `sharp` etc now?
> 
> Yep! Starting from `vite-plugin-electron-renderer@0.10.2` again, external libraries are built-in support. 👉 [example](https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.10.3/examples/quick-start/vite.config.ts?rgh-link-date=2023-01-15T08%3A56%3A12Z#L14-L23)
> 
> ```js
> {
>   plugins: [
>     renderer({
>       // Enables use of Node.js API in the Renderer-process
>       nodeIntegration: true,
>       // Like Vite's pre bundling
>       optimizeDeps: {
>         include: [
>           'sharp', // Here
>         ],
>       },
>     }),
>   ],
> }
> ```
> 
> > Also do we really have to load these dependencies and if so, why? I never quite understood that. [f70971d](https://github.com/WeakAuras/WeakAuras-Companion/commit/f70971d273f8c731ad42d05b03c76edf66707079)
> 
> This is not required, it optimizes the size of the APP package after the build.

Got it, thank you! I applied this and it lookes like `archiver` does not like it:

`Uncaught Error: Cannot find module 'readdir-glob'`

Error on my side or worth a ticket?

**Comment by caoxiemeihao** [comment]
Typing `shamefully-hoist=true` to `.npmrc` file.

https://github.com/electron-vite/electron-vite-react/blob/main/.npmrc

**Comment by caoxiemeihao** [comment]
Typing `shamefully-hoist=true` to `.npmrc` file.

https://github.com/electron-vite/electron-vite-react/blob/main/.npmrc

**Comment by Stanzilla** [comment]
> Typing `shamefully-hoist=true` to `.npmrc` file.
> 
> [electron-vite/electron-vite-react@`main`/.npmrc](https://github.com/electron-vite/electron-vite-react/blob/main/.npmrc?rgh-link-date=2023-01-16T01%3A32%3A49Z)

Okay that lead to the next issue:

`"defineStore" is not exported by "pinia", imported by "packages/renderer/src/stores/config.ts".` (https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/3926402311/jobs/6712086461)

I also tried a fresh branch (https://github.com/WeakAuras/WeakAuras-Companion/tree/v5_2) that more closely mirrors the newer examples you have, there I get stuck at 

```
Uncaught Error: Cannot find module 'readable-stream/passthrough'
Require stack:
- /home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/node_modules/lazystream/lib/lazystream.js
- /home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/node_modules/archiver-utils/index.js
- /home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/node_modules/archiver/lib/core.js
- /home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/node_modules/archiver/index.js
- /home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/dist/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3833)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/node_modules/lazystream/lib/lazystream.js:2:19)
    at Object.<anonymous> (/home/stan/projects/personal/WeakAurasCompanion/release/5.0.0/linux-unpacked/resources/app.asar/node_modules/lazystream/lib/lazystream.js:56:3)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

**Comment by caoxiemeihao** [comment]
image

Using `pnpm` may not solve this problem well. `yarn` works fine.

**Comment by Stanzilla** [comment]
@caoxiemeihao any hints as to how I can use top level await with your setup? What I currently have does not work because it would require the index to be cjs which seems to be impossible?

**Comment by caoxiemeihao** [comment]
You can use esm format in Renderer.

**Comment by Stanzilla** [comment]
> You can use esm format in Renderer.

I tried, is this not how you do it? https://github.com/WeakAuras/WeakAuras-Companion/pull/1421/commits/996992d9b83a27be62e75ca03200d1dbc786d91a#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR106

**Comment by Stanzilla** [comment]
@caoxiemeihao everything seems to work in dev mode now but when packaged, it can't find/use node API, any ideas?

> Uncaught TypeError: Failed to resolve module specifier "path". Relative references must start with either "/", "./", or "../".

**Comment by caoxiemeihao** [comment]
> Uncaught TypeError: Failed to resolve module specifier "path". Relative references must start with either "/", "./", or "../".

Fixed it in #1773

**Pull request merged**
